apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karyakram-ingress
  annotations:
    # Provisions a public ALB on AWS
    alb.ingress.kubernetes.io/scheme: internet-facing
    
    # Routes directly to Pod IPs inside the VPC (highly recommended for EKS)
    alb.ingress.kubernetes.io/target-type: ip
    
    # Configures health check path for target groups
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          # Route API calls to the Express backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: karyakram-backend-service
                port:
                  number: 4000
          # Route all other web traffic to Next.js
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karyakram-frontend-service
                port:
                  number: 3000
